main: me.benrobson.zanderhub.ZanderHubMain
name: zander-hub
version: 1.0
author: Ben Robson
api-version: 1.16
softdepend:
  - PremiumVanish

commands:
  fly:
    description: Allows player to fly.
    usage: /fly
  connect:
    description: Connect to a Server.
    usage: /connect <server>

permissions:
  zander.fly:
    default: op
  zanderhub.administrator:
    default: op
  zanderhub.build:
    default: op